const weatherCode = {
  0: { text: 'tornado', icon: '🌪' },
  1: { text: 'tropical storm', icon: '💨' },
  2: { text: 'hurricane', icon: '💨'},
  3: { text: 'severe thunderstorms', icon: '⛈' },
  4: { text: 'thunderstorms', icon: '⛈' },
  5: { text: 'mixed rain and snow', icon: '🌨' },
  6: { text: 'mixed rain and sleet', icon: '🌧' },
  7: { text: 'mixed snow and sleet', icon: '🌨' },
  8: { text: 'freezing drizzle', icon: '🌧' },
  9: { text: 'drizzle', icon: '🌧' },
  10: { text: 'freezing rain', icon: '🌧' },
  11: { text: 'showers', icon: '🌧' },
  12: { text: 'showers', icon: '🌧' },
  13: { text: 'snow flurries', icon: '🌨' },
  14: { text: 'light snow showers', icon: '🌨' },
  15: { text: 'blowing snow', icon: '🌨' },
  16: { text: 'snow', icon: '🌨' },
  17: { text: 'hail', icon: '🌨' },
  18: { text: 'sleet', icon: '🌧' },
  19: { text: 'dust', icon: '🌫' },
  20: { text: 'foggy', icon: '🌫' },
  21: { text: 'haze', icon: '🌫' },
  22: { text: 'smoky', icon: '🌫' },
  23: { text:'blustery', icon: '💨' },
  24: { text:'windy', icon: '💨' },
  25: { text:'cody', icon: '❄️' },
  26: { text:'cloudy', icon: '☁️' },
  27: { text:'mostly cloudy (night)', icon: '☁️' },
  28: { text:'mostly cloudy (day)', icon: '🌥' },
  29: { text:'partly cloudy (night)', icon: '☁️' },
  30: { text:'partly cloudy (day)', icon: '⛅️' },
  31: { text:'clear (night)', icon: '🌙' },
  32: { text:'sunny', icon: '☀️' },
  33: { text:'fair (night)', icon: '🌙' },
  34: { text:'fair (day)', icon: '🌤' },
  35: { text: 'mixed rain and hail', icon: '🌧' },
  36: { text:'hot', icon: '☀️' },
  37: { text: 'isolated thunderstorms', icon: '⛈' },
  38: { text: 'scattered thunderstorms', icon: '⛈' },
  39: { text: 'scattered thunderstorms', icon: '⛈' },
  40: { text: 'scattered showers', icon: '🌧' },
  41: { text: 'heavy snow', icon: '🌨' },
  42: { text: 'scattered snow showers', icon: '🌨' },
  43: { text: 'heavy snow', icon: '🌨' },
  44: { text:'partly cloudy', icon: '⛅️' },
  45: { text: 'thundershowers', icon: '⛈' },
  46: { text: 'snow showers', icon: '🌨' },
  47: { text: 'isolated thundershowers', icon: '⛈' },
  3200: { text: 'not available', icon: '🈚️' }
};

const weaterEmoji = (code) => {
  return weatherCode[code].icon;
};

export default weaterEmoji;
